### PR TITLE
Add A PlaceHolder And Change Button Styling

### PR DESCRIPTION
**Pull request by kratin01**
At line 182, I suggest substituting the <h2> tag with a more visually appealing placeholder element to enhance the overall design of the webpage. Furthermore, I recommend applying a set of CSS styles to the primary buttons, including 'Refresh,' 'Repeat,' 'Custom Text,' and 'Clear Text,' to give them a more sophisticated and professional appearance. This will greatly improve the initial impression of the buttons and contribute to the overall aesthetic quality of the page.

### CODE REVIEW

**Comment by HauseMasterZ** [comment]
Your design is good but maybe it goes against my minimalistic approach?

**Comment by kratin01** [comment]
Thank you for your input. My intention was to enhance the user experience by making buttons more approachable without compromising the minimalist aesthetic.. I'm open to adjustments that better align with the project's aesthetic. Please share any specific suggestions or guidelines, and I'll make the necessary changes. Your feedback is valued

**Comment by HauseMasterZ** [comment]
> Thank you for your input. My intention was to enhance the user experience by making buttons more approachable without compromising the minimalist aesthetic.. I'm open to adjustments that better align with the project's aesthetic. Please share any specific suggestions or guidelines, and I'll make the necessary changes. Your feedback is valued

Am thinking changing the shapes of the buttons, and if colors need to be changes rather than changing for each button change them for all of them uniformly in the stylesheet itself. Rounded corners might also look better.

**Comment by kratin01** [comment]
Thanks for your feedback! I've made the changes according to your suggestions, and I really hope that it meets your expectations. If there's anything else that needs improvement, please don't hesitate to let me know. I'm always here to help and make things better for you!

**Comment by HauseMasterZ** [comment]
LGTM, Will merge.

**Comment by HauseMasterZ** [comment]
LGTM

**Pull request merged**
